---
namespace: "zloveless"
name: "containers"
description: ""
version: "1.0.0"
readme: "README.md"
authors:
  - "Zack Loveless (https://zloveless.com)"
license_file: "LICENSE"
repository: "https://github.com/zloveless/ansible-containers"

dependencies:
  "community.docker": ">=1.10.0"
